### ISSUE TITLE
Any Requirements Tools to open Android Project.

### ISSUE THREAD

**Issue by dldpidodido** [nintendaii/UnityNotifPlugin#1]
Hi Nintendaii,

It was successfully working on my android Phone. Then when I was trying to edit the code using android studio it was not working when I try to build a bundle (.aar) file. I got an error I don't know yet if you use Android Studio or another version. Please advise what tools you used or a requirements 

Thank you.

**Comment by nintendaii** [comment]
Hi, can you please say what exact error appears when you try to build your .aar file? I used Android Studio 4.1.2 for my builds
