### ISSUE TITLE
Does this require installing the Bridge as a separate APK, or is it somehow included in the Unity Build APK?

### ISSUE THREAD

**Issue by jakedowns** [nintendaii/UnityNotifPlugin#11]
just curious how this works. is this a separate apk that you need to build/install, or is it part of the apk that unity builds?

**Comment by nintendaii** [comment]
The plugin is just a .aar file that u have to put in unity project Assets/Plugins/... Then, when u make an actual build, the logic of your app AND plugin as well is included in the final Unity .apk file. So the answer is: it is a part of unity .apk

**Comment by jakedowns** [comment]
awesome, thanks. gonna try this out.
