### ISSUE TITLE
Date range

### ISSUE THREAD

**Issue by CliffCalist** [nintendaii/UnityNotifPlugin#17]
Hello. Glory to Ukraine! Although I have 4 years of experience, I have not created anything similar before. I mean .arr to use it in Unity later. I understood the main idea, but I have some questions.

1. I suspect that I can see and edit the code of your .arr through Android Studio. Is this a correct assumption?
2. I am developing a step counter game with daily statistics. Your asset generally fits my needs, but can I run the service for a certain period of time? Or is it better to run it at an indefinite time and get the number of steps for a specific date?
I need to enter the number of steps into the data of a column chart to display it for each day separately. So far, I have only seen that I can start a session and see the number of steps specifically for that session, without being tied to a date.

**Comment by foobar-git** [comment]
Bro, leave the political b.s. off these sites. We are brothers and sisters in coding and we deal only with programming issues here.
