### ISSUE TITLE
Minimum API Level

### ISSUE THREAD

**Issue by elephantmobiledev** [nintendaii/UnityNotifPlugin#3]
Hi.

I used the Sample Scene in Unity. I selected minimum API level 21 and i got this error.

![resim_2021-04-03_061235](https://user-images.githubusercontent.com/76541405/113466323-95178b80-9443-11eb-8286-148635b76124.png)

I couldn't find Android Manifest in the Assets. Can you help me please?

**Comment by nintendaii** [comment]
Greetings! You can not select API level smaller than 26. If you want you can try to change the minimum API level in Android project of the app. When you open the Android project in Android Studio you should follow this instruction: https://abhiandroid.com/androidstudio/change-api-sdk-level-android-studio.html. Also, you should keep in mind that Unity minimum API level must match with Android minimum API.

**Comment by elephantmobiledev** [comment]
Thank you so much for help me. That works!

I am developing an app like a music player and i want that when users minimize it, it keeps run in the background. I think i can make possible this with your plugin. What do you think about that?

**Comment by nintendaii** [comment]
You welcome. 

I think you can achieve the goal using this plugin. The best option for music player is to handle the playback on the Android side. If you will have any other questions about plugin, feel free to ask me.
Also, it would be very nice to see the result of your work in the future :)

**Comment by nintendaii** [comment]
I will close this issue. If you want to ask more, please open new issue or direct message me (email in the profile description).
