### ISSUE TITLE
Step Counter 

### ISSUE THREAD

**Issue by MTCpersian** [nintendaii/UnityNotifPlugin#4]
Hi
I cloned your git and open Unity3DProject in unity and build an APK on my phone. the start and stop service work but step counter dont work. 
Q: I have a Bluetooth which I get data from it in unity and save and do work on that data, I wanted to know how can I get data that data during background service??
Thanks for your time!

**Comment by nintendaii** [comment]
Greetings! Sorry for the late response. 
What device are you using? Make sure that it is above 26 API.
About your Bluetooth question. What do you mean by you have a Bluetooth? Could you please tell more about what are you doing in your project? You should keep in mind that all operations in background should be done in the Android side. This means that you should implement Bluetooth functionality on the Android side OR simply send your data to the background service and handle the data there. Anyway, it depends on what exactly are u doing and when do you receive data from Bluetooth.
Regards.

**Comment by MTCpersian** [comment]
Thanks for the response!
I'm using Samsung A51. 
I have Health care device which I connect to it via Bluetooth using this https://assetstore.unity.com/packages/tools/network/bluetooth-le-for-ios-tvos-and-android-26661 asset! 
Getting some info from that device such as gyroscope and analyze data and save it! Problem is when I unfocused from my app or minimize it the app wont receive data and app cant do what I want in background!
Thanks for the help in advance

**Comment by nintendaii** [comment]
I think you should debug the StepCounter service in Android Studio and see what error occurs while debugging. There might be some problems with permissions. You can check my answer to the previous issue https://github.com/nintendaii/unity-background-service/issues/2#issuecomment-802304847.
About BT. If a plugin you are using from the Asset Store is not running in the background, contact the developer of that plugin. As I said before, "all operations in background should be done in the Android side. This means that you should implement Bluetooth functionality on the Android side OR simply send your data to the background service and handle the data there."
