### ISSUE TITLE
Test app crashes with Start Service

### ISSUE THREAD

**Issue by AnthonyGirdler** [nintendaii/UnityNotifPlugin#9]
Installed the app via an apk transfer to my phone and it crashes when I press Start Service.
The app closes and the background service does not start. There's nothing in the notification area.

**Comment by CrandellWS** [comment]
Do to the age of this project I would guess it is a permissions problem thing and you are testing on newer phone. Maybe try again on older phone to see...

I will be loading this project up sometime in the next few weeks and I will know better then what is happening...

**Comment by ffrxsln** [comment]
> Installed the app via an apk transfer to my phone and it crashes when I press Start Service. The app closes and the background service does not start. There's nothing in the notification area.

https://github.com/ffrxsln/unity-background-service-updated/releases/tag/0.1

**Comment by nintendaii** [comment]
Hey guys, sorry for so late reply, I didn’t saw any notifications from GitHub) It looks like @ffrxsln fixed the issue for android 12 crash on his forked project. One interesting detail is that on my Samsung M31 (Android 12) it didn’t crashed at all. Looks like this issue is device specific.

**Comment by nintendaii** [comment]
@AnthonyGirdler please, test the solution provided by @ffrxsln and let me know the result
